name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'Client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      working-directory: ./Client
      run: npm install

    - name: Build the app
      working-directory: ./Client
      run: npm run build

  docker_build_and_push:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./Client
        file: ./Client/Dockerfile
        push: true
        tags: docker.io/${{ secrets.DOCKER_USERNAME }}/blog-app-frontend:latest
