name: Frontend CI

# Trigger the workflow on push and pull requests to the 'main' branch for changes in the 'Client' folder
on:
  push:
    branches:
      - main
    paths:
      - 'Client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to set up Node.js 16.x
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # Step to install dependencies in the 'Client' directory
      - name: Install dependencies
        working-directory: ./Client
        run: npm install

      # Step to build the application in the 'Client' directory
      - name: Build the app
        working-directory: ./Client
        run: npm run build

  docker_build_and_push:
    runs-on: ubuntu-latest

    # The 'docker_build_and_push' job will only run if the 'build' job is successful
    needs: build

    steps:
      # Step to checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to build the Docker image
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # Step to log in to Docker Hub
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step to push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
