name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'Client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Client/**'

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      working-directory: ./Client
      run: npm install

    - name: Build the app
      working-directory: ./Client
      run: npm run build


      # - name: upload to docker hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./Client
      #     file: ./Client/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

