name: Frontend CI

# Trigger the workflow on push and pull requests to the 'main' branch for changes in the 'Client' folder
on:
  push:
    branches:
      - main
    paths:
      - 'Client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step to checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step to set up Node.js 16.x
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    # Step to install dependencies in the 'Client' directory
    - name: Install dependencies
      working-directory: ./Client
      run: npm install

    # Step to build the application in the 'Client' directory
    - name: Build the app
      working-directory: ./Client
      run: npm run build

  docker_build_and_push:
    runs-on: ubuntu-latest

    # The 'docker_build_and_push' job will only run if the 'build' job is successful
    needs: build

    steps:
    # Step to checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Optional step to set up QEMU for multi-platform builds
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    # Optional step to set up Docker Buildx for advanced Docker builds
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3


    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: hemanthgangula/blog-app-frontend
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step to log in to Docker Hub using credentials stored in GitHub secrets
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # Step to build and push the Docker image to Docker Hub
    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: ./Client
    #     file: ./Client/Dockerfile
    #     push: true
    #     tags: docker.io/${{ secrets.DOCKER_USERNAME }}/blog-app-frontend:latest
